name: Trivy Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run some tests with Trivy
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        trivy-config: trivy.yaml

    - name: Build Docker image
      run: docker build -f Containerfile -t local-nginx .

    - name: Run Trivy vulnerability scanner in image mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'image'
        image-ref: 'local-nginx'